[theme]
primaryColor="#D4AF37"
backgroundColor="#f0f0f5"
secondaryBackgroundColor="#E9EAEC"
textColor="#262730"
font="sans serif"

[server]
port = 8503
enableStaticServing = true

[browser]
gatherUsageStats = false
